* both matrix must contain same number of cols

In [55]:
import numpy as np


In [2]:
a=np.random.randint(1,1000,10)
b=np.random.randint(1,100,(3,9))
print(a)
print(b)


[ 24 579 286 123 137 892 200 774 135 705]
[[ 8 45 17 70  2 92 50 75 21]
 [11 61 52  3 10  3 30  5 36]
 [37 99 45 93 87  2 60  4 21]]


# min
* function =min which is used for the minimum element
# argmin
* argmin provides the index of the minimum element

In [5]:
print(np.min(a))
print(np.argmin(a))
print(np.min(b))
print(np.argmin(b))

24
0
2
4


In [10]:
print(np.max(a))
print(np.argmax(a))
print(np.max(b))
print(np.argmax(b))
print(np.max(b,axis=1)) # for row wise minimum element
print(np.max(b,axis=0)) #for column wise

892
5
99
19
[92 61 99]
[37 99 52 93 87 92 60 75 36]


In [9]:
print(np.min(a,axis=0))
print(np.argmin(a))
print(np.min(b,axis=1))
print(np.argmin(b)) #for the minimum element of each rows used axis

24
0
[2 3 2]
4


In [11]:
print(np.sum(a))#return sum of all elemnets present in arg array
print(np.sum(b)) #return sum of all elements present in arg array
print(np.sum(b,axis=1))
print(np.sum(b,axis=0))

3855
1039
[380 211 448]
[ 56 205 114 166  99  97 140  84  78]


In [12]:
print(np.mean(a)) #returns arithmetic avg of all elements present in arg array
                 
print(np.mean(b)) #returns arithmetic avg of all elements present in arg array
print(np.mean(b,axis=1)) #returns arithmetic avg of all elements present in arg row
print(np.mean(b,axis=0)) #returns arithmetic avg of all elements present in arg column

385.5
38.48148148148148
[42.22222222 23.44444444 49.77777778]
[18.66666667 68.33333333 38.         55.33333333 33.         32.33333333
 46.66666667 28.         26.        ]


In [15]:
print(np.sort(a)) # for sorting the array 
print(np.sort(b ,axis=1)) # for row wise sorting

print(np.sort(b ,axis=0)) #for the column wise sorting
#sorts the array in the assecending order

[ 24 123 135 137 200 286 579 705 774 892]
[[ 2  8 17 21 45 50 70 75 92]
 [ 3  3  5 10 11 30 36 52 61]
 [ 2  4 21 37 45 60 87 93 99]]
[[ 8 45 17  3  2  2 30  4 21]
 [11 61 45 70 10  3 50  5 21]
 [37 99 52 93 87 92 60 75 36]]


In [17]:
np.square(a)
print(a)

[ 24 579 286 123 137 892 200 774 135 705]


In [18]:
print(a)

[ 24 579 286 123 137 892 200 774 135 705]


In [19]:
np.square(a) #for squaring the array we use the square fuction 

array([   576, 335241,  81796,  15129,  18769, 795664,  40000, 599076,
        18225, 497025], dtype=int32)

In [20]:
np.square(b)

array([[  64, 2025,  289, 4900,    4, 8464, 2500, 5625,  441],
       [ 121, 3721, 2704,    9,  100,    9,  900,   25, 1296],
       [1369, 9801, 2025, 8649, 7569,    4, 3600,   16,  441]],
      dtype=int32)

In [23]:
np.sqrt(a) #for finding the square root of the array we use the sqrr function


array([ 4.89897949, 24.06241883, 16.91153453, 11.09053651, 11.70469991,
       29.86636905, 14.14213562, 27.82085549, 11.61895004, 26.55183609])

In [24]:
np.round(a_sqrt,2)

NameError: name 'a_sqrt' is not defined

In [25]:
print(a_sqrt)

NameError: name 'a_sqrt' is not defined

In [26]:
a_sqrt=np.sqrt(a)

In [27]:
print(a_sqrt)

[ 4.89897949 24.06241883 16.91153453 11.09053651 11.70469991 29.86636905
 14.14213562 27.82085549 11.61895004 26.55183609]


In [28]:
print(a_sqrt,2)

[ 4.89897949 24.06241883 16.91153453 11.09053651 11.70469991 29.86636905
 14.14213562 27.82085549 11.61895004 26.55183609] 2


In [29]:
np.round(a_sqrt,2) # for rounding off the we use the round function

array([ 4.9 , 24.06, 16.91, 11.09, 11.7 , 29.87, 14.14, 27.82, 11.62,
       26.55])

In [30]:
np.round(np.sqrt(a),2)

array([ 4.9 , 24.06, 16.91, 11.09, 11.7 , 29.87, 14.14, 27.82, 11.62,
       26.55])

## log
* for log computation we use the log function
* it is uses when the base is e

In [33]:
np.log(a)


array([3.17805383, 6.36130248, 5.65599181, 4.81218436, 4.91998093,
       6.79346613, 5.29831737, 6.65157187, 4.90527478, 6.5581978 ])

In [34]:
np.log10(a)

array([1.38021124, 2.76267856, 2.45636603, 2.08990511, 2.13672057,
       2.95036485, 2.30103   , 2.88874096, 2.13033377, 2.84818912])

In [37]:
print(b)

[[ 8 45 17 70  2 92 50 75 21]
 [11 61 52  3 10  3 30  5 36]
 [37 99 45 93 87  2 60  4 21]]


## Transpose func

In [39]:
np.transpose(b)

array([[ 8, 11, 37],
       [45, 61, 99],
       [17, 52, 45],
       [70,  3, 93],
       [ 2, 10, 87],
       [92,  3,  2],
       [50, 30, 60],
       [75,  5,  4],
       [21, 36, 21]])

In [41]:
b.T # it is  also used for transposing of the matrix

array([[ 8, 11, 37],
       [45, 61, 99],
       [17, 52, 45],
       [70,  3, 93],
       [ 2, 10, 87],
       [92,  3,  2],
       [50, 30, 60],
       [75,  5,  4],
       [21, 36, 21]])

## numpy fun v/s array method

In [42]:
a

array([ 24, 579, 286, 123, 137, 892, 200, 774, 135, 705])

In [43]:
np.sum(a) # numpy function

3855

In [44]:
a.sum() #array method

3855

In [49]:
x=[3,35,2,5]
np.mean(x)
np.sum(x)


45

In [50]:
np.median(a)

243.0

In [52]:
print(b)

[[ 8 45 17 70  2 92 50 75 21]
 [11 61 52  3 10  3 30  5 36]
 [37 99 45 93 87  2 60  4 21]]


In [58]:
a=np.random.randint(1,5,(3,3))
b=np.random.randint(1,5,(3,3))
print(a)
print(b)

[[3 4 1]
 [2 3 2]
 [4 3 2]]
[[4 3 3]
 [2 4 4]
 [1 3 4]]


In [59]:
a*b

array([[12, 12,  3],
       [ 4, 12,  8],
       [ 4,  9,  8]])

In [60]:
np.dot(a,b)

array([[21, 28, 29],
       [16, 24, 26],
       [24, 30, 32]])

#  @ used as a dot product

In [61]:
a@b

array([[21, 28, 29],
       [16, 24, 26],
       [24, 30, 32]])

In [62]:
a=np.loadtxt("file path" ,delimiter=',',dtype=np.int32) # it is used for 

OSError: file path not found.

In [63]:
np.round(np.sqrt(a),2)

array([[1.73, 2.  , 1.  ],
       [1.41, 1.73, 1.41],
       [2.  , 1.73, 1.41]])

In [64]:
np.savetxt("file path",a,newline=',',fmt="%.2f")

# labeled data 
* have column name and row have index 
* pandas dataframe




# unlabeled data
* numpy matrix